---
render_scale: 2
max_correspondence_distances: [0.3, 0.15, 0.1, 0.06, 0.03]
num_dummy_points: 50
dummy_weights: 0.1
optimize_every_n_iters: 1
use_adaptive_weights: true
filter_observed_pts: true
add_physical_constraints: true
add_ground_constraints: true
save: false
