---
render_scale: 1
max_correspondence_distances: [0.4, 0.3, 0.25, 0.2, 0.15, 0.1, 0.07, 0.05, 0.05, 0.05]
num_dummy_points: 50
dummy_weights: 0.5
optimize_every_n_iters: 1
use_adaptive_weights: true
filter_observed_pts: true
add_physical_constraints: true
add_ground_constraints: false
visualize: true
save: false
